--USE [DW_SysExpert]
--GO

--/****** Object:  Table [dbo].[PedimentoFacturaPartida]    Script Date: 08/10/2020 03:35:12 p. m. ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

DROP TABLE [dbo].[PedimentoFacturaPartida]

CREATE TABLE [dbo].[PedimentoFacturaPartida](
	[IdPedimentoFacturaPartida] [int] IDENTITY(1,1) NOT NULL,
	[IdPedimentoFactura] [int] NOT NULL,
	[idPartida] [int] NOT NULL,
	[idFactura] [int] NOT NULL,
	[idParte] [int] NULL,
	[Descripcion] [varchar](250) NOT NULL,
	[Marca] [varchar](80) NULL,
	[Modelo] [varchar](80) NULL,
	[NoSerie] [varchar](25) NULL,
	[CantidadComercial] [float] NOT NULL,
	[idUEA] [int] NULL,
	[UnidadMedidaComercialClaveIUnidad] [smallint] NULL,
	[UnidadMedidaComercialDescripcion] [varchar](30) NULL,
	[UnidadMedidaComercialAbreviacion] [varchar](30) NULL,
	[UnidadMedidaComercialAbreviacion2] [varchar](30) NULL,
	[UnidadMedidaComercialClaveCOVE] [varchar](10) NULL,
	[UnidadMedidaComercialUEAOVEValidas] [varchar](100) NULL,
	[ImporteME] [float] NOT NULL,
	[ImporteUSD] [float] NOT NULL,
	[ValorEAiaME] [float] NOT NULL,
	[ValorEAiaUSD] [float] NOT NULL,
	[ValorAgregadoUSD] [float] NOT NULL,
	[PesoBruto] [float] NOT NULL,
	[idPaisOrigen] [int] NULL,
	[PaisOrigenClaveM3] [varchar](3) NULL,
	[PaisOrigenNombrePais] [varchar](60) NULL,
	[idFraccion] [int] NULL,
	[TIGIEFraccion] [varchar](10) NULL,
	[TIGIEtg_Descripcion] [varchar](250) NULL,
	[TIGIEidUnidad] [int] NULL,
	[TGIEUnidadClaveIUnidad] [smallint] NULL,
	[TGIEUnidadDescripcion] [varchar](30) NULL,
	[TGIEUnidadAbreviacion] [varchar](30) NULL,
	[TGIEUnidadAbreviacion2] [varchar](30) NULL,
	[TGIEUnidadClaveCOVE] [varchar](10) NULL,
	[TGIEUnidadUEAOVEValidas] [varchar](100) NULL,
	[CantidaIEPSrifa] [float] NOT NULL,
	[idIdentificador] [int] NULL,
	[IdentificadorIdentificador] [varchar](3) NULL,
	[IdentificadoritDescripcion] [varchar](500) NULL,
	[IdentificadorNivel] [varchar](1) NULL,
	[Complemento] [varchar](30) NULL,
	[Desaduanamiento] [varchar](8) NULL,
	[idOrdenFraccion] [int] NULL,
	[PedFraccionidFraccion] [int] NOT NULL,
	[PedFraccionTIGIEFraccion] [varchar](10) NULL,
	[PedFraccionTIGIEtg_Descripcion] [varchar](250) NULL,
	[PedFraccionTIGIEidUnidad] [int] NULL,
	[PedFraccionTGIEUnidadClaveIUnidad] [smallint] NULL,
	[PedFraccionTGIEUnidadDescripcion] [varchar](30) NULL,
	[PedFraccionTGIEUnidadAbreviacion] [varchar](30) NULL,
	[PedFraccionTGIEUnidadAbreviacion2] [varchar](30) NULL,
	[PedFraccionTGIEUnidadClaveCOVE] [varchar](10) NULL,
	[PedFraccionTGIEUnidadUEAOVEValidas] [varchar](100) NULL,
	[PedFraccionDescripcion] [varchar](250) NOT NULL,
	[PedFraccionMarca] [varchar](80) NOT NULL,
	[PedFraccionModelo] [varchar](80) NOT NULL,
	[PedFraccionNoSerie] [varchar](20) NOT NULL,
	[PedFraccionCodigoProducto] [varchar](20) NOT NULL,
	[PedFraccionPesoBruto] [decimal](14, 3) NOT NULL,
	[PedFraccionCantidadComercial] [decimal](15, 3) NOT NULL,
	[PedFraccionidUEA] [int] NULL,
	[PedFraccionUnidadMedidaComercialClaveIUnidad] [smallint] NULL,
	[PedFraccionUnidadMedidaComercialDescripcion] [varchar](30) NULL,
	[PedFraccionUnidadMedidaComercialAbreviacion] [varchar](30) NULL,
	[PedFraccionUnidadMedidaComercialAbreviacion2] [varchar](30) NULL,
	[PedFraccionUnidadMedidaComercialClaveCOVE] [varchar](10) NULL,
	[PedFraccionUnidadMedidaComercialUEAOVEValidas] [varchar](100) NULL,
	[PedFraccionCantidaIEPSrifa] [float] NOT NULL,
	[PedFraccionidPaisOrigen] [int] NOT NULL,
	[PedFraccionPaisOrigenClaveM3] [varchar](3) NULL,
	[PedFraccionPaisOrigenNombrePais] [varchar](60) NULL,
	[PedFraccionidPaisVendedor] [int] NOT NULL,
	[PedFraccionPaisVendedorClaveM3] [varchar](3) NULL,
	[PedFraccionPaisVendedorNombrePais] [varchar](60) NULL,
	[PedFraccionidPaisMoneda] [int] NULL,
	[PedFraccionPaisMonedaClaveM3] [varchar](3) NULL,
	[PedFraccionPaisMonedaNombrePais] [varchar](60) NULL,
	[PedFraccionPaisMonedaClaveMoneda] [varchar](3) NULL,
	[PedFraccionPaisMonedaNombreMoneda] [varchar](30) NULL,
	[PedFraccionImporteME] [money] NOT NULL,
	[PedFraccionValorAgregado] [money] NOT NULL,
	[PedFraccionidValoracion] [int] NOT NULL,
	[PedFraccionValoracionClaveValoracion] [smallint] NULL,
	[PedFraccionValoracionmv_Descripcion] [varchar](60) NULL,
	[PedFraccionObservaciones] [varchar](4096) NOT NULL,
	[PedFraccionidVinculacion] [int] NOT NULL,
	[PedFraccionVinculacionClave] [varchar](1) NOT NULL,
	[PedFraccionidVinculacionDescripcion] [varchar](60) NOT NULL,
	[PedFraccionSubdivision] [int] NOT NULL,
	[PedFraccionValorEAiaNoOriginaria] [int] NOT NULL,
	[PedFraccionMontoIGI] [int] NOT NULL,
	[PedFraccionArancelEUACAN] [int] NOT NULL,
	[PedFraccionMontoExento] [int] NOT NULL,
	[PedFraccionValorFactura] [bigint] NULL,
	[PedFraccionValorAduana] [bigint] NULL,
	[PedFraccionValorDolares] [money] NOT NULL,
	[PedFraccionLongDescripcion] [tinyint] NOT NULL,
	[PedFraccionORDEN] [int] NULL,
	[PedFraccionValorAduanaCuentaAduanera] [int] NULL,
	[PedFraccionValorRetorno] [decimal](18, 2) NULL,
	[PedFraccionidPaisProcedencia] [int] NULL,
	[PedFraccionPaisProcedenciaClaveM3] [varchar](3) NULL,
	[PedFraccionPaisProcedenciaNombrePais] [varchar](60) NULL,
	[PedFraccionNuevasObservaciones] [text] NULL,
	
	[PedFraccionContribucionDTAidFracContribuciones][INT] NULL,
	[PedFraccionContribucionDTAPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionDTAidFormaPago] [int] NULL,
	[PedFraccionContribucionDTAFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionDTAFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionDTAidTipoTasa] [int] NULL,
	[PedFraccionContribucionDTATipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionDTATipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionDTATasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionDTAidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionDTAAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionDTAAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionDTAPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionDTAFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionDTAidFracContribCA][INT] NULL,
	[PedFraccionContribucionDTACaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionDTATasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionDTAidContribucionCompensacion][INT],
	[PedFraccionContribucionDTAContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionDTAContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionDTAContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionDTAMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionCCidFracContribuciones][INT] NULL,
	[PedFraccionContribucionCCPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionCCidFormaPago] [int] NULL,
	[PedFraccionContribucionCCFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionCCFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionCCidTipoTasa] [int] NULL,
	[PedFraccionContribucionCCTipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionCCTipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionCCTasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionCCidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionCCAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionCCAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionCCPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionCCFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionCCidFracContribCA][INT] NULL,
	[PedFraccionContribucionCCCaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionCCTasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionCCidContribucionCompensacion][INT],
	[PedFraccionContribucionCCContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionCCContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionCCContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionCCMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionIVAidFracContribuciones][INT] NULL,
	[PedFraccionContribucionIVAPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionIVAidFormaPago] [int] NULL,
	[PedFraccionContribucionIVAFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionIVAFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionIVAidTipoTasa] [int] NULL,
	[PedFraccionContribucionIVATipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionIVATipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionIVATasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionIVAidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionIVAAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionIVAAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionIVAPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionIVAFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionIVAidFracContribCA][INT] NULL,
	[PedFraccionContribucionIVACaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionIVATasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionIVAidContribucionCompensacion][INT],
	[PedFraccionContribucionIVAContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionIVAContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionIVAContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionIVAMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionISANidFracContribuciones][INT] NULL,
	[PedFraccionContribucionISANPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionISANidFormaPago] [int] NULL,
	[PedFraccionContribucionISANFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionISANFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionISANidTipoTasa] [int] NULL,
	[PedFraccionContribucionISANTipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionISANTipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionISANTasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionISANidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionISANAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionISANAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionISANPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionISANFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionISANidFracContribCA][INT] NULL,
	[PedFraccionContribucionISANCaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionISANTasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionISANidContribucionCompensacion][INT],
	[PedFraccionContribucionISANContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionISANContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionISANContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionISANMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionIEPSidFracContribuciones][INT] NULL,
	[PedFraccionContribucionIEPSPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionIEPSidFormaPago] [int] NULL,
	[PedFraccionContribucionIEPSFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionIEPSFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionIEPSidTipoTasa] [int] NULL,
	[PedFraccionContribucionIEPSTipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionIEPSTipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionIEPSTasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionIEPSidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionIEPSAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionIEPSAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionIEPSPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionIEPSFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionIEPSidFracContribCA][INT] NULL,
	[PedFraccionContribucionIEPSCaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionIEPSTasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionIEPSidContribucionCompensacion][INT],
	[PedFraccionContribucionIEPSContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionIEPSContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionIEPSContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionIEPSMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionIGI/IGEidFracContribuciones][INT] NULL,
	[PedFraccionContribucionIGI/IGEPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionIGI/IGEidFormaPago] [int] NULL,
	[PedFraccionContribucionIGI/IGEFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionIGI/IGEFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionIGI/IGEidTipoTasa] [int] NULL,
	[PedFraccionContribucionIGI/IGETipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionIGI/IGETipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionIGI/IGETasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionIGI/IGEidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionIGI/IGEAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionIGI/IGEAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionIGI/IGEPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionIGI/IGEFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionIGI/IGEidFracContribCA][INT] NULL,
	[PedFraccionContribucionIGI/IGECaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionIGI/IGETasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionIGI/IGEidContribucionCompensacion][INT],
	[PedFraccionContribucionIGI/IGEContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionIGI/IGEContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionIGI/IGEContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionIGI/IGEMargenDiscriminacion][FLOAT],

	[PedFraccionContribucion303idFracContribuciones][INT] NULL,
	[PedFraccionContribucion303PorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucion303idFormaPago] [int] NULL,
	[PedFraccionContribucion303FormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucion303FormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucion303idTipoTasa] [int] NULL,
	[PedFraccionContribucion303TipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucion303TipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucion303TasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucion303idAduanaCompensacion] [int] NULL,
	[PedFraccionContribucion303AduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucion303AduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucion303PedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucion303FechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucion303idFracContribCA][INT] NULL,
	[PedFraccionContribucion303CaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucion303TasaReferencia][FLOAT] NULL,
	[PedFraccionContribucion303idContribucionCompensacion][INT],
	[PedFraccionContribucion303ContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucion303ContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucion303ContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucion303MargenDiscriminacion][FLOAT],

	[PedFraccionContribucion25idFracContribuciones][INT] NULL,
	[PedFraccionContribucion25PorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucion25idFormaPago] [int] NULL,
	[PedFraccionContribucion25FormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucion25FormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucion25idTipoTasa] [int] NULL,
	[PedFraccionContribucion25TipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucion25TipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucion25TasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucion25idAduanaCompensacion] [int] NULL,
	[PedFraccionContribucion25AduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucion25AduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucion25PedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucion25FechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucion25idFracContribCA][INT] NULL,
	[PedFraccionContribucion25CaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucion25TasaReferencia][FLOAT] NULL,
	[PedFraccionContribucion25idContribucionCompensacion][INT],
	[PedFraccionContribucion25ContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucion25ContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucion25ContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucion25MargenDiscriminacion][FLOAT],

	[PedFraccionContribucionEURidFracContribuciones][INT] NULL,
	[PedFraccionContribucionEURPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionEURidFormaPago] [int] NULL,
	[PedFraccionContribucionEURFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionEURFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionEURidTipoTasa] [int] NULL,
	[PedFraccionContribucionEURTipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionEURTipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionEURTasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionEURidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionEURAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionEURAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionEURPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionEURFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionEURidFracContribCA][INT] NULL,
	[PedFraccionContribucionEURCaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionEURTasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionEURidContribucionCompensacion][INT],
	[PedFraccionContribucionEURContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionEURContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionEURContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionEURMargenDiscriminacion][FLOAT],

	[PedFraccionContribucionMTidFracContribuciones][INT] NULL,
	[PedFraccionContribucionMTPorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucionMTidFormaPago] [int] NULL,
	[PedFraccionContribucionMTFormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucionMTFormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucionMTidTipoTasa] [int] NULL,
	[PedFraccionContribucionMTTipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucionMTTipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucionMTTasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucionMTidAduanaCompensacion] [int] NULL,
	[PedFraccionContribucionMTAduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucionMTAduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucionMTPedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucionMTFechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucionMTidFracContribCA][INT] NULL,
	[PedFraccionContribucionMTCaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucionMTTasaReferencia][FLOAT] NULL,
	[PedFraccionContribucionMTidContribucionCompensacion][INT],
	[PedFraccionContribucionMTContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucionMTContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucionMTContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucionMTMargenDiscriminacion][FLOAT],

	[PedFraccionContribucion2IA2idFracContribuciones][INT] NULL,
	[PedFraccionContribucion2IA2PorcentajeAplicacion][DECIMAL](18, 2) NULL,		
	[PedFraccionContribucion2IA2idFormaPago] [int] NULL,
	[PedFraccionContribucion2IA2FormaPagoClaveFormaPago] [smallint] NULL,
	[PedFraccionContribucion2IA2FormaPagofp_Descripcion] [varchar](35) NULL,
	[PedFraccionContribucion2IA2idTipoTasa] [int] NULL,
	[PedFraccionContribucion2IA2TipoTastaTipoTasa] [smallint] NULL,
	[PedFraccionContribucion2IA2TipoTasaDescripcion] [varchar](51) NULL,
	[PedFraccionContribucion2IA2TasaContribucion] [decimal](12, 5) NULL,
	[PedFraccionContribucion2IA2idAduanaCompensacion] [int] NULL,
	[PedFraccionContribucion2IA2AduanaCompensacionClaveAduana] [varchar](3) NULL,
	[PedFraccionContribucion2IA2AduanaCompensacionNombreAduana] [nchar](130) NULL,
	[PedFraccionContribucion2IA2PedimentoCompensacion][varchar](12) NULL,
	[PedFraccionContribucion2IA2FechaCompensacion] [DATETIME] NULL,
	[PedFraccionContribucion2IA2idFracContribCA][INT] NULL,
	[PedFraccionContribucion2IA2CaracteristicasCalculo][TINYINT] NULL,
	[PedFraccionContribucion2IA2TasaReferencia][FLOAT] NULL,
	[PedFraccionContribucion2IA2idContribucionCompensacion][INT],
	[PedFraccionContribucion2IA2ContribucionCompensacionClaveContribucion][SMALLINT],
	[PedFraccionContribucion2IA2ContribucionCompensacionct_Descripcion][VARCHAR](120),
	[PedFraccionContribucion2IA2ContribucionCompensacionAbreviacion][VARCHAR](10),
	[PedFraccionContribucion2IA2MargenDiscriminacion][FLOAT],
	
	[PedFraccionIdentificadorZCidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorZCidIdentificador][INT] NULL,
	[PedFraccionIdentificadorZCIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorZCIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorZCIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorZCComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorZCComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorZCComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorPAidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorPAidIdentificador][INT] NULL,
	[PedFraccionIdentificadorPAIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorPAIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorPAIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorPAComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorPAComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorPAComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorGAidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorGAidIdentificador][INT] NULL,
	[PedFraccionIdentificadorGAIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorGAIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorGAIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorGAComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorGAComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorGAComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorCIidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorCIidIdentificador][INT] NULL,
	[PedFraccionIdentificadorCIIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorCIIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorCIIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorCIComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorCIComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorCIComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorMVidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorMVidIdentificador][INT] NULL,
	[PedFraccionIdentificadorMVIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorMVIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorMVIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorMVComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorMVComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorMVComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorENidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorENidIdentificador][INT] NULL,
	[PedFraccionIdentificadorENIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorENIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorENIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorENComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorENComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorENComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorMAidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorMAidIdentificador][INT] NULL,
	[PedFraccionIdentificadorMAIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorMAIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorMAIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorMAComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorMAComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorMAComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorMMidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorMMidIdentificador][INT] NULL,
	[PedFraccionIdentificadorMMIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorMMIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorMMIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorMEAomplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorMEAomplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorMEAomplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorALidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorALidIdentificador][INT] NULL,
	[PedFraccionIdentificadorALIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorALIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorALIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorALComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorALComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorALComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorEPidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorEPidIdentificador][INT] NULL,
	[PedFraccionIdentificadorEPIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorEPIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorEPIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorEPComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorEPComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorEPComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorNSidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorNSidIdentificador][INT] NULL,
	[PedFraccionIdentificadorNSIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorNSIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorNSIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorNSComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorNSComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorNSComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorMBidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorMBidIdentificador][INT] NULL,
	[PedFraccionIdentificadorMBIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorMBIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorMBIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorMBComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorMBComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorMBComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorMCidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorMCidIdentificador][INT] NULL,
	[PedFraccionIdentificadorMCIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorMCIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorMCIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorMCComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorMCComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorMCComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorTLidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorTLidIdentificador][INT] NULL,
	[PedFraccionIdentificadorTLIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorTLIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorTLIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorTLComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorTLComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorTLComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorESidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorESidIdentificador][INT] NULL,
	[PedFraccionIdentificadorESIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorESIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorESIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorESComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorESComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorESComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorEAidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorEAidIdentificador][INT] NULL,
	[PedFraccionIdentificadorEAIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorEAIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorEAIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorEAComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorEAComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorEAComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorPGidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorPGidIdentificador][INT] NULL,
	[PedFraccionIdentificadorPGIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorPGIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorPGIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorPGComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorPGComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorPGComplemento3][VARCHAR](40) NULL,

	[PedFraccionIdentificadorPGidIdentificadorFraccion][INT] NULL,
	[PedFraccionIdentificadorPGidIdentificador][INT] NULL,
	[PedFraccionIdentificadorPGIdentificadorIdentificador][VARCHAR](3) NULL,
	[PedFraccionIdentificadorPGIdentificadorit_Descripcion][VARCHAR](500) NULL,
	[PedFraccionIdentificadorPGIdentificadorDescripcionComplemento][VARCHAR](450) NULL,
	[PedFraccionIdentificadorPGComplemento][VARCHAR](30) NULL,
	[PedFraccionIdentificadorPGComplemento2][VARCHAR](50) NULL,
	[PedFraccionIdentificadorPGComplemento3][VARCHAR](40) NULL,

	[idRemesa] [int] NULL,
	[idReferencia] [int] NULL,
	[CantidadSaldo] [float] NOT NULL,
	[Explosionado] [bit] NOT NULL,
	[EstatusPPS] [int] NULL,
	[NOTA_1] [varchar](100) NULL,
	[NOTA_2] [varchar](100) NULL,
	[NOTA_3] [varchar](100) NULL,
	[NOTA_4] [varchar](100) NULL,
	[NOTA_5] [varchar](100) NULL,
	[PrecioUnitario] [decimal](20, 6) NULL,
	[ValorNoOriginario] [decimal](18, 2) NULL,
	[ValorRetorno] [decimal](18, 2) NULL,
	[Commodity] [char](4) NULL,
	[Bultos] [int] NULL,
	[idPartidaOriginal] [int] NULL,
	[OrdenCompra] [varchar](30) NULL,
	[idIdentificador2] [int] NULL,
	[Identificador2Identificador] [varchar](3) NULL,
	[Identificador2itDescripcion] [varchar](500) NULL,
	[Identificador2Nivel] [varchar](1) NULL,
	[Complemento2_1] [varchar](30) NULL,
	[Complemento2_2] [varchar](50) NULL,
	[Comlpemento2_3] [varchar](40) NULL,
	[idIdentificador3] [int] NULL,
	[Identificador3Identificador] [varchar](3) NULL,
	[Identificador3itDescripcion] [varchar](500) NULL,
	[Identificador3Nivel] [varchar](1) NULL,
	[Complemento3_1] [varchar](30) NULL,
	[Complemento3_2] [varchar](50) NULL,
	[Complemento3_3] [varchar](40) NULL,
	[idUnidadCOVE] [int] NULL,
	[UnidadCOVEClave] [varchar](10) NULL,
	[UnidadCOVEDescripcion] [varchar](100) NULL,
	[UnidadCOVEAbreviacion] [varchar](30) NULL,
	[CantidadCOVE] [float] NULL,
	[DescripcionCOVE] [varchar](255) NULL,
	[idValoracion] [int] NULL,
	[ValoracionClaveValoracion] [smallint] NULL,
	[Valoracionmv_Descripcion] [varchar](60) NULL,
	[ValorCOVE] [decimal](20, 6) NULL,
	[subModelo] [varchar](50) NULL,
	[Lote] [varchar](50) NULL,
	[POCantidad] [int] NULL,
	[PartePreCaptura] [varchar](30) NULL,
	[CertificaOrigen] [varchar](50) NULL,
	[Complemento2] [varchar](50) NULL,
	[Complemento3] [varchar](40) NULL,
	[idCategoria] [int] NULL,
	[idTipoDeMercancia] [int] NULL,
	[TipoDeMercancia] [int] NULL,
	[TipoDeMercanciaClave] [varchar](6) NULL,
	[TipoDeMercanciaDescripcion] [varchar](60) NULL,
	[TipoDeMercanciaClaveTipoMercancia] [varchar](3) NULL,
	[TipoDeMercanciaNombreTipoMercancia] [varchar](3) NULL,
 CONSTRAINT [PK_PedimentoFacturaPartida] PRIMARY KEY CLUSTERED 
(
	[IdPedimentoFacturaPartida] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PedimentoFacturaPartida]  WITH CHECK ADD  CONSTRAINT [FK_PedimentoFacturaPartida_PedimentoFactura] FOREIGN KEY([IdPedimentoFactura])
REFERENCES [dbo].[PedimentoFactura] ([IdPedimentoFactura])
GO

ALTER TABLE [dbo].[PedimentoFacturaPartida] CHECK CONSTRAINT [FK_PedimentoFacturaPartida_PedimentoFactura]
GO


