USE [SysExpertBackup]

SELECT TOP 1000
            PEDFACTURAS.idFactura [idFactura]
           ,PEDFACTURAS.idReferencia [idReferencia]
           ,PEDFACTURAS.idRemesa [idRemesa]
           ,PEDFACTURAS.idGuia [idGuia]
           ,PEDGUIAS.idGuia [GuiaidGuia]
           ,PEDGUIAS.GuiaMaster [GuiaGuiaMaster]
           ,PEDGUIAS.GuiaHouse [GuiaGuiaHouse]
           ,PEDGUIAS.Fecha [GuiaFecha]
           ,PEDGUIAS.idTransportMaster [GuiaidTransportMaster]
           ,PEDGUIASTRM.Clave [GuiaTransportMasterClave]
           ,PEDGUIASTRM.Nombre [GuiaTransportMasterNombre]
           ,PEDGUIAS.idTransportHouse [GuiaidTransportHouse]
           ,PEDGUIASTRH.Clave [GuiaTransportHouseClave]
           ,PEDGUIASTRH.Nombre [GuiaTransportHouserNombre]
           ,PEDGUIAS.idOperacion [GuiaidOperacion]
           ,PEDGUIASOP.TipoOperacion [GuiaOperacionTipoOperacion]
           ,PEDGUIASOP.op_Clave [GuiaOperacionop_Clave]
           ,PEDGUIASOP.op_Descripcion [GuiaOperacionop_Descripcion]
           ,PEDGUIAS.Bultos [GuiaBultos]
           ,PEDGUIAS.Arribo [GuiaArribo]
           ,PEDGUIAS.idBultos [GuiaidBultos]
           ,PEDGUIAS.idAgencia [GuiaidAgencia]
           ,PEDGUIASAG.Patente [GuiaAgenciaPatente]
           ,PEDGUIASAGAD.idAduana [GuiaAgenciaAduanaidAduana]
           ,PEDGUIASAGAD.ClaveAduana [GuiaAgenciaAduanaClaveAduana]
           ,PEDGUIASAGAD.NombreAduana [GuiaAgenciaAduanaNombreAduana]
           ,PEDGUIAS.IdenTranspoMaster [GuiaIdenTranspoMaster]
           ,PEDGUIAS.IdenTranspoHouse [GuiaIdenTranspoHouse]
           ,PEDGUIAS.idPaisTransporMaster [GuiaidPaisTransporMaster]
           ,PEDGUIASPTM.ClaveM3 [GuiaPaisTransporMasterClaveM3]
           ,PEDGUIASPTM.NombrePais [GuiaPaisTransporMasterNombrePais]
           ,PEDGUIAS.idTransportHouse [GuiaidPaisTransporHouse]
           ,PEDGUIASPTH.ClaveM3 [GuiaPaisTransporHouseClaveM3]
           ,PEDGUIASPTH.NombrePais [GuiaPaisTransporHouseNombrePais]
           ,PEDGUIAS.idGuiaObservacion [GuiaidGuiaObservacion]
           ,PEDGUIASOG.Clave [GuiaidGuiaObservacionClave]
           ,PEDGUIASOG.Observacion [GuiaidGuiaObservacionObservacion]
           ,PEDGUIAS.idPrioridad [GuiaidPrioridad]
           ,PEDGUIASPG.Clave [GuiaPrioridadClave]
           ,PEDGUIASPG.Prioridad [GuiaPrioridadPrioridad]
           ,Null [GuiaidReferencia]								-- Revisar lo de Bultos
           ,NULL [GuiaReferenciaNumeroReferencia]
           ,Null [GuiaReferenciaNumeroPedimento]
           ,NULL [GuiaReferenciaFechaEntrada]
           ,NULL [GuiaReferenciaFechaPresentacion]
           ,NULL [GuiaReferenciaFechaPago]
           ,PEDGUIAS.Anticipo [GuiaAnticipo]
           ,PEDGUIAS.AnticipoRecibo [GuiaAnticipoRecibo]
           ,PEDGUIAS.AnticipoCheque [GuiaAnticipoCheque]
           ,PEDGUIAS.AnticipoFecha [GuiaAnticipoFecha]
           ,PEDGUIAS.AnticipoidBanco [GuiaAnticipoidBanco]
           ,PEDGUIASBA.Clave [GuiaAnticipoBancoClave]
           ,PEDGUIASBA.Nombre [GuiaAnticipoBancoNombre]
           ,PEDGUIAS.PesoBruto [GuiaPesoBruto]
           ,PEDGUIAS.Folio [GuiaFolio]
           ,PEDGUIAS.Importe [GuiaImporte]
           ,PEDGUIAS.RegistroUTF [GuiaRegistroUTF]
           ,PEDGUIAS.idCliente [GuiaidCliente]
           ,PEDGUIASCLI.ClaveCliente [GuiaClienteClaveCliente]
           ,PEDGUIASCLI.RazonSocial [GuiaClienteRazonSocial]
           ,PEDGUIASCLI.RFC [GuiaClienteRFC]
           ,PEDGUIASCLI.CURP [GuiaClienteCURP]
           ,PEDGUIASCLI.Domicilio [GuiaClienteDomicilio]
           ,PEDGUIASCLI.Calle [GuiaClienteCalle]
           ,PEDGUIASCLI.NumeroExterior [GuiaClienteNumeroExterior]
           ,PEDGUIASCLI.NumeroInterior [GuiaClienteNumeroInterior]
           ,PEDGUIASCLI.Colonia [GuiaClienteColonia]
           ,PEDGUIASCLI.CodigoPostal [GuiaClienteCodigoPostal]
           ,PEDGUIASCLI.Ciudad [GuiaClienteCiudad]
           ,PEDGUIASCLI.idEntidad [GuiaClienteidEntidad]
           ,PEDGUIASCLIEF.ClaveEntidad [GuiaClienteClaveEntidad]
           ,PEDGUIASCLIEF.EntidadFederativa [GuiaClienteEntidadFederativa]
           ,PEDGUIASCLI.idPais [GuiaClienteidPais]
           ,PEDGUIASCLIPAIS.ClaveM3 [GuiaClientePaisClaveM3]
           ,PEDGUIASCLIPAIS.NombrePais [GuiaClientePaisNombrePais]
           ,PEDGUIAS.Subdivision [GuiaSubdivision]
           ,PEDGUIAS.Control [GuiaControl]
           ,PEDGUIAS.idPuerto [GuiaidPuerto]
           ,PEDGUIASPU.Clave [GuiaPuertoClave]
           ,PEDGUIASPU.Puerto [GuiaPuertoPuerto]
		   ,PEDGUIAESTGUIASENVDOC.idClavesEstatusGuias [GuiaEstatusEnvioDocumentosidEstatusGuia]
		   ,PEDGUIAESTGUIASENVDOC.Fecha                [GuiaEstatusEnvioDocumentosFecha]
		   ,PEDGUIAESTGUIASENVDOC.Hora                 [GuiaEstatusEnvioDocumentosHora]
		   ,PEDGUIAESTGUIASENVDOC.Observaciones        [GuiaEstatusEnvioDocumentosObservaciones]
		   ,PEDGUIAESTGUIASCAPPED.idClavesEstatusGuias [GuiaEstatusCapturaPedimentoidEstatusGuia]
		   ,PEDGUIAESTGUIASCAPPED.Fecha                [GuiaEstatusCapturaPedimentoFecha]
		   ,PEDGUIAESTGUIASCAPPED.Hora                 [GuiaEstatusCapturaPedimentoHora]
		   ,PEDGUIAESTGUIASCAPPED.Observaciones        [GuiaEstatusCapturaPedimentoObservaciones]
		   ,PEDGUIAESTGUIASREVPED.idClavesEstatusGuias [GuiaEstatusRevisionPedimentoidEstatusGuia]
		   ,PEDGUIAESTGUIASREVPED.Fecha                [GuiaEstatusRevisionPedimentoFecha]
		   ,PEDGUIAESTGUIASREVPED.Hora                 [GuiaEstatusRevisionPedimentoHora]
		   ,PEDGUIAESTGUIASREVPED.Observaciones        [GuiaEstatusRevisionPedimentoObservaciones]
		   ,PEDGUIAESTGUIASREVCEM.idClavesEstatusGuias [GuiaEstatusRevalidacionConocimientoEmbarqueidEstatusGuia]
		   ,PEDGUIAESTGUIASREVCEM.Fecha                [GuiaEstatusRevalidacionConocimientoEmbarqueFecha]
		   ,PEDGUIAESTGUIASREVCEM.Hora                 [GuiaEstatusRevalidacionConocimientoEmbarqueHora]
		   ,PEDGUIAESTGUIASREVCEM.Observaciones        [GuiaEstatusRevalidacionConocimientoEmbarqueObservaciones]
		   ,PEDGUIAESTGUIASPROPRE.idClavesEstatusGuias [GuiaEstatusProgramacionPrevioReconocimientoidEstatusGuia]
		   ,PEDGUIAESTGUIASPROPRE.Fecha                [GuiaEstatusProgramacionPrevioReconocimientoFecha]
		   ,PEDGUIAESTGUIASPROPRE.Hora                 [GuiaEstatusProgramacionPrevioReconocimientoHora]
		   ,PEDGUIAESTGUIASPROPRE.Observaciones        [GuiaEstatusProgramacionPrevioReconocimientoObservaciones]
		   ,PEDGUIAESTGUIASPRODES.idClavesEstatusGuias [GuiaEstatusProgramacionDespachoidEstatusGuia]
		   ,PEDGUIAESTGUIASPRODES.Fecha                [GuiaEstatusProgramacionDespachoFecha]
		   ,PEDGUIAESTGUIASPRODES.Hora                 [GuiaEstatusProgramacionDespachoHora]
		   ,PEDGUIAESTGUIASPRODES.Observaciones        [GuiaEstatusProgramacionDespachoObservaciones]
		   ,PEDGUIAESTGUIASENTCVA.idClavesEstatusGuias [GuiaEstatusEntregaContenedorVacioidEstatusGuia]
		   ,PEDGUIAESTGUIASENTCVA.Fecha                [GuiaEstatusEntregaContenedorVacioFecha]
		   ,PEDGUIAESTGUIASENTCVA.Hora                 [GuiaEstatusEntregaContenedorVacioHora]
		   ,PEDGUIAESTGUIASENTCVA.Observaciones        [GuiaEstatusEntregaContenedorVacioObservaciones]
		   ,PEDGUIAESTGUIASPRECAP.idClavesEstatusGuias [GuiaEstatusPreCapturaidEstatusGuia]
		   ,PEDGUIAESTGUIASPRECAP.Fecha                [GuiaEstatusPreCapturaFecha]
		   ,PEDGUIAESTGUIASPRECAP.Hora                 [GuiaEstatusPreCapturaHora]
		   ,PEDGUIAESTGUIASPRECAP.Observaciones        [GuiaEstatusPreCapturaObservaciones]
		   ,PEDGUIAESTGUIASCIECON.idClavesEstatusGuias [GuiaEstatusCierreConsolidadoidEstatusGuia]
		   ,PEDGUIAESTGUIASCIECON.Fecha                [GuiaEstatusCierreConsolidadoFecha]
		   ,PEDGUIAESTGUIASCIECON.Hora                 [GuiaEstatusCierreConsolidadoHora]
		   ,PEDGUIAESTGUIASCIECON.Observaciones        [GuiaEstatusCierreConsolidadoObservaciones]
		   ,PEDGUIAESTGUIASPROTRA.idClavesEstatusGuias [GuiaEstatusProgramacionTransferenciaidEstatusGuia]
		   ,PEDGUIAESTGUIASPROTRA.Fecha                [GuiaEstatusProgramacionTransferenciaFecha]
		   ,PEDGUIAESTGUIASPROTRA.Hora                 [GuiaEstatusProgramacionTransferenciaHora]
		   ,PEDGUIAESTGUIASPROTRA.Observaciones        [GuiaEstatusProgramacionTransferenciaObservaciones]
		   ,PEDFACTURAS.NumeroFactura [NumeroFactura]
           ,PEDFACTURAS.FechaFactura [FechaFactura]
           ,PEDFACTURAS.FechaEntPres [FechaEntPres]
           ,PEDFACTURAS.idIncoterm [idIncoterm]
           ,PEDFACINCO.Incoterm [IncotermIncoterm]
           ,PEDFACINCO.inc_Descripcion [Incoterminc_Descripcion]
           ,PEDFACTURAS.idPaisMoneda [idPaisMoneda]
           ,PEDFACPAISM.ClaveM3 [PaisMonedaClaveM3]
           ,PEDFACPAISM.NombrePais [PaisMonedaNombrePais]
           ,PEDFACTURAS.idProveedor [idProveedor]
           ,PEDFACPR.ClaveProveedor [ProveedorClaveProveedor]
           ,PEDFACPR.RazonSocial [ProveedorRazonSocial]
           ,PEDFACPR.TaxNumber [ProveedorTaxNumber]
           ,PEDFACPR.RFC [ProveedorRFC]
           ,PEDFACPR.CURP [ProveedorCURP]
           ,PEDFACPR.Calle [ProveedorCalle]
           ,PEDFACPR.NumeroExterior [ProveedorNumeroExterior]
           ,PEDFACPR.NumeroInterior [ProveedorNumeroInterior]
           ,PEDFACPR.Colonia [ProveedorColonia]
           ,PEDFACPR.CodigoPostal [ProveedorCodigoPostal]
           ,PEDFACPR.Ciudad [ProveedorCiudad]
           ,PEDFACPR.idEntidad [ProveedoridEntidad]
           ,PEDFACPREF.ClaveEntidad [ProveedorEntidadClaveEntidad]
           ,PEDFACPREF.EntidadFederativa [ProveedorEntidadEntidadFederativa]
           ,PEDFACPR.idPais [ProveedoridPais]
           ,PEDFACPRPAIS.ClaveM3 [ProveedorPaisClaveM3]
           ,PEDFACPRPAIS.NombrePais [ProveedorPaisNombrePais]
           ,PEDFACPR.email [Proveedoremail]
           ,PEDFACPR.NumExportadorConfiable [ProveedorNumExportadorConfiable]
           ,PEDFACPR.ClaveExternaExport [ProveedorClaveExternaExport]
           ,PEDFACPR.NumOperadorEconomico [ProveedorNumOperadorEconomico]
           ,PEDFACTURAS.idDestinatario [idDestinatario]
           ,PEDFACDES.ClaveProveedor [DestinatarioClaveProveedor]
           ,PEDFACDES.RazonSocial [DestinatarioRazonSocial]
           ,PEDFACDES.TaxNumber [DestinatarioTaxNumber]
           ,PEDFACDES.RFC [DestinatarioRFC]
           ,PEDFACDES.CURP [DestinatarioCURP]
           ,PEDFACDES.Calle [DestinatarioCalle]
           ,PEDFACDES.NumeroExterior [DestinatarioNumeroExterior]
           ,PEDFACDES.NumeroInterior [DestinatarioNumeroInterior]
           ,PEDFACDES.Colonia [DestinatarioColonia]
           ,PEDFACDES.CodigoPostal [DestinatarioCodigoPostal]
           ,PEDFACDES.Ciudad [DestinatarioCiudad]
           ,PEDFACDES.idEntidad [DestinatarioidEntidad]
           ,PEDFACDESEF.ClaveEntidad [DestinatarioEntidadClaveEntidad]
           ,PEDFACDESEF.EntidadFederativa [DestinatarioEntidadEntidadFederativa]
           ,PEDFACDES.idPais [DestinatarioidPais]
           ,PEDFACDESPAIS.ClaveM3 [DestinatarioPaisClaveM3]
           ,PEDFACDESPAIS.NombrePais [DestinatarioPaisNombrePais]
           ,PEDFACDES.email [Destinatarioemail]
           ,PEDFACDES.NumExportadorConfiable [DestinatarioNumExportadorConfiable]
           ,PEDFACDES.ClaveExternaExport [DestinatarioClaveExternaExport]
           ,PEDFACDES.NumOperadorEconomico [DestinatarioNumOperadorEconomico]
           ,PEDFACTURAS.FletesUSD [FletesUSD]
           ,PEDFACTURAS.SegurosUSD [SegurosUSD]
           ,PEDFACTURAS.EmbalajeUSD [EmbalajeUSD]
           ,PEDFACTURAS.OtrosIncrementUSD [OtrosIncrementUSD]
           ,PEDFACTURAS.idValoracion [idValoracion]
           ,PEDFACMV.ClaveValoracion [ValoracionClaveValoracion]
           ,PEDFACMV.mv_Descripcion [Valoracionmv_Descripcion]
           ,PEDFACTURAS.P_O [P_O]
           ,PEDFACTURAS.Notas [Notas]
           ,PEDFACTURAS.idCliente [idCliente]
           ,PEDFACCLI.ClaveCliente [ClienteClaveCliente]
           ,PEDFACCLI.RazonSocial [ClienteRazonSocial]
           ,PEDFACCLI.RFC [ClienteRFC]
           ,PEDFACCLI.CURP [ClienteCURP]
           ,PEDFACCLI.Domicilio [ClienteDomicilio]
           ,PEDFACCLI.Calle [ClienteCalle]
           ,PEDFACCLI.NumeroExterior [ClienteNumeroExterior]
           ,PEDFACCLI.NumeroInterior [ClienteNumeroInterior]
           ,PEDFACCLI.Colonia [ClienteColonia]
           ,PEDFACCLI.CodigoPostal [ClienteCodigoPostal]
           ,PEDFACCLI.Ciudad [ClienteCiudad]
           ,PEDFACCLI.idEntidad [ClienteidEntidad]
           ,PEDFACCLIEF.ClaveEntidad [ClienteClaveEntidad]
           ,PEDFACCLIEF.EntidadFederativa [ClienteEntidadFederativa]
           ,PEDFACCLI.idPais [ClienteidPais]
           ,PEDFACCLIPAIS.ClaveM3 [ClientePaisClaveM3]
           ,PEDFACCLIPAIS.NombrePais [ClientePaisNombrePais]
           ,PEDFACTURAS.TipoOperacion [TipoOperacion]
           ,PEDFACTURAS.idAgencia [idAgencia]
           ,PEDFACAG.Patente [AgenciaPatente]
           ,PEDFACAG.idAduana [AgenciaAduanaidAduana]
           ,PEDFACAGAD.ClaveAduana [AgenciaAduanaClaveAduana]
           ,PEDFACAGAD.nombreAduana [AgenciaAduanaNombreAduana]
           ,PEDFACTURAS.ImporteUSD [ImporteUSD]
           ,PEDFACTURAS.ImporteME [ImporteME]
           ,PEDFACTURAS.ValorMciaME [ValorMciaME]
           ,PEDFACTURAS.ValorMciaUSD [ValorMciaUSD]
           ,PEDFACTURAS.ValorAgregadoUSD [ValorAgregadoUSD]
           ,PEDFACTURAS.PesoBruto [PesoBruto]
           ,PEDFACTURAS.idEquivalencia [idEquivalencia]
           ,PEDFACMONEQ.Fecha [EquivalenciaFecha]
           ,PEDFACMONEQ.Equivalencia [Equivalencia]
           ,PEDFACTURAS.idEstatus [idEstatus]
           ,PEDFACESTFAC.Clave [EstatusClave]
           ,PEDFACESTFAC.Estatus [EstatusEstatus]
           ,PEDFACTURAS.idPaisProveedor [idPaisProveedor]
           ,PEDFACPAISPROV.ClaveM3 [PaisProveedorPaisClaveM3]
           ,PEDFACPAISPROV.NombrePais [PaisProveedorPaisNombrePais]
           ,PEDFACTURAS.idPaisProcedencia [idPaisProcedencia]
           ,PEDFACPAISPROC.ClaveM3 [PaisProcedenciaPaisClaveM3]
           ,PEDFACPAISPROC.NombrePais [PaisProcedenciaPaisNombrePais]
           ,PEDFACTURAS.idVinculacion [idVinculacion]
           ,PEDFACTIPOSVIN.Clave [VinculacionClave]
           ,PEDFACTIPOSVIN.Descripcion [VinculacionDescripcion]
           ,PEDFACTURAS.Subdivision [Subdivision]
           ,PEDFACTURAS.idCentroCosto [idCentroCosto]
           ,PEDFACCENTROCOS.CentroCosto [CentroCostoCentroCosto]
           ,PEDFACCENTROCOS.Ejecutivo [CentroCostoEjecutivo]
           ,PEDFACTURAS.fungeCertificado [fungeCertificado]
           ,PEDFACTURAS.FletesME [FletesME]
           ,PEDFACTURAS.SegurosME [SegurosME]
           ,PEDFACTURAS.EmbalajeME [EmbalajeME]
           ,PEDFACTURAS.OtrosIncrementME [OtrosIncrementME]
           ,PEDFACTURAS.idPaisMonFletes [idPaisMonFletes]
           ,PEDFACTURAS.idPaisMonSeguros [idPaisMonSeguros]
           ,PEDFACPAISMONSE.ClaveM3 [PaisMonSegurosClaveM3]
           ,PEDFACPAISMONSE.NombrePais [PaisMonSegurosNombrePais]
           ,PEDFACPAISMONSE.ClaveMoneda [PaisMonSegurosClaveMoneda]
           ,PEDFACPAISMONSE.NombreMoneda [PaisMonSegurosNombreMoneda]
           ,PEDFACTURAS.idPaisMonEmbalaje [idPaisMonEmbalaje]
           ,PEDFACPAISMONEM.ClaveM3 [PaisMonEmbalajeClaveM3]
           ,PEDFACPAISMONEM.NombrePais [PaisMonEmbalajeNombrePais]
           ,PEDFACPAISMONEM.ClaveMoneda [PaisMonEmbalajeClaveMoneda]
           ,PEDFACPAISMONEM.NombreMoneda [PaisMonEmbalajeNombreMoneda]
           ,PEDFACTURAS.idPaisMonOtrosIncrement [idPaisMonOtrosIncrement]
           ,PEDFACPAISMONOI.ClaveM3 [PaisMonOtrosIncrementClaveM3]
           ,PEDFACPAISMONOI.NombrePais [PaisMonOtrosIncrementNombrePais]
           ,PEDFACPAISMONOI.ClaveMoneda [PaisMonOtrosIncrementClaveMoneda]
           ,PEDFACPAISMONOI.NombreMoneda [PaisMonOtrosIncrementNombreMoneda]
           ,PEDFACTURAS.BultosFactura [BultosFactura]
           ,PEDFACTURAS.Notas2 [Notas2]
           ,PEDFACTURAS.Enajenacion [Enajenacion]
           ,PEDFACTURAS.ComplementoAduanal [ComplementoAduanal]
           ,PEDFACTURAS.FacturaOriginal [FacturaOriginal]
           ,PEDFACTURAS.ProForma [ProForma]
           ,PEDFACTURAS.TotalManual [TotalManual]
           ,PEDFACTURAS.CertificaOrigen [CertificaOrigen]
FROM Ped_Facturas PEDFACTURAS
	LEFT JOIN Ped_Guias             PEDGUIAS        WITH(NOLOCK) ON (PEDFACTURAS.idGuia            = PEDGUIAS.idGuia)
	LEFT JOIN Transportistas        PEDGUIASTRM     WITH(NOLOCK) ON (PEDGUIAS.idTransportMaster    = PEDGUIASTRM.idTransportista)				-- Revisar
	LEFT JOIN Transportistas        PEDGUIASTRH     WITH(NOLOCK) ON (PEDGUIAS.idTransportMaster    = PEDGUIASTRH.idTransportista)				-- Revisar
	LEFT JOIN Operaciones           PEDGUIASOP      WITH(NOLOCK) ON (PEDGUIAS.idOperacion          = PEDGUIASOP.idTipoOperacion)
	LEFT JOIN Agencias              PEDGUIASAG      WITH(NOLOCK) ON (PEDGUIAS.idAgencia            = PEDGUIASAG.IdAgencia)
	LEFT JOIN Aduanas               PEDGUIASAGAD    WITH(NOLOCK) ON (PEDGUIASAG.idAgencia          = PEDGUIASAGAD.idAduana)
	LEFT JOIN Paises                PEDGUIASPTM     WITH(NOLOCK) ON (PEDGUIAS.idPaisTransporMaster = PEDGUIASPTM.idPais)
	LEFT JOIN Paises                PEDGUIASPTH     WITH(NOLOCK) ON (PEDGUIAS.idPaisTransporMaster = PEDGUIASPTH.idPais)
	LEFT JOIN ObservacionesGuia     PEDGUIASOG      WITH(NOLOCK) ON (PEDGUIAS.idGuiaObservacion    = PEDGUIASOG.idGuiaObservacion)
	LEFT JOIN PrioridadesGuia       PEDGUIASPG      WITH(NOLOCK) ON (PEDGUIAS.idPrioridad          = PEDGUIASPG.idPrioridad)
	LEFT JOIN Clientes              PEDGUIASCLI     WITH(NOLOCK) ON (PEDGUIAS.idCliente            = PEDGUIASCLI.idCliente)
	LEFT JOIN EntidadesFederativas  PEDGUIASCLIEF   WITH(NOLOCK) ON (PEDGUIASCLI.idEntidad         = PEDGUIASCLIEF.idEntidad)
	LEFT JOIN Paises                PEDGUIASCLIPAIS WITH(NOLOCK) ON (PEDGUIASCLI.idPais            = PEDGUIASCLIPAIS.idPais)
	LEFT JOIN Bancos                PEDGUIASBA      WITH(NOLOCK) ON (PEDGUIAS.AnticipoidBanco      = PEDGUIASBA.idBanco)
	LEFT JOIN Puertos               PEDGUIASPU      WITH(NOLOCK) ON (PEDGUIAS.idPuerto             = PEDGUIASPU.idPuerto)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASENVDOC   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASENVDOC.idGuia AND PEDGUIAESTGUIASENVDOC.idClavesEstatusGuias = 2)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASCAPPED   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASCAPPED.idGuia AND PEDGUIAESTGUIASCAPPED.idClavesEstatusGuias = 3)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASREVPED   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASREVPED.idGuia AND PEDGUIAESTGUIASREVPED.idClavesEstatusGuias = 4)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASREVCEM   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASREVCEM.idGuia AND PEDGUIAESTGUIASREVCEM.idClavesEstatusGuias = 5)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASPROPRE   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASPROPRE.idGuia AND PEDGUIAESTGUIASPROPRE.idClavesEstatusGuias = 6)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASPRODES   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASPRODES.idGuia AND PEDGUIAESTGUIASPRODES.idClavesEstatusGuias = 7)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASENTCVA   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASENTCVA.idGuia AND PEDGUIAESTGUIASENTCVA.idClavesEstatusGuias = 11)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASPRECAP   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASPRECAP.idGuia AND PEDGUIAESTGUIASPRECAP.idClavesEstatusGuias = 27)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASCIECON   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASCIECON.idGuia AND PEDGUIAESTGUIASCIECON.idClavesEstatusGuias = 29)
	LEFT JOIN EstatusGuias  PEDGUIAESTGUIASPROTRA   WITH(NOLOCK) ON (PEDGUIAS.idGuia = PEDGUIAESTGUIASPROTRA.idGuia AND PEDGUIAESTGUIASPROTRA.idClavesEstatusGuias = 31)
	LEFT JOIN Incoterms             PEDFACINCO      WITH(NOLOCK) ON (PEDFACTURAS.idIncoterm        = PEDFACINCO.idIncoterm)
	LEFT JOIN Paises                PEDFACPAISM     WITH(NOLOCK) ON (PEDFACTURAS.idPaisMoneda      = PEDFACPAISM.idPais)
	LEFT JOIN Proveedores           PEDFACPR        WITH(NOLOCK) ON (PEDFACTURAS.idProveedor       = PEDFACPR.idProveedor)
	LEFT JOIN EntidadesFederativas  PEDFACPREF      WITH(NOLOCK) ON (PEDFACPR.idEntidad            = PEDFACPREF.idEntidad)
	LEFT JOIN Paises                PEDFACPRPAIS    WITH(NOLOCK) ON (PEDFACPR.idPais               = PEDFACPRPAIS.idPais)
	LEFT JOIN Proveedores           PEDFACDES       WITH(NOLOCK) ON (PEDFACTURAS.idDestinatario    = PEDFACDES.idProveedor)
	LEFT JOIN EntidadesFederativas  PEDFACDESEF     WITH(NOLOCK) ON (PEDFACDES.idEntidad           = PEDFACDESEF.idEntidad)
	LEFT JOIN Paises                PEDFACDESPAIS   WITH(NOLOCK) ON (PEDFACDES.idPais              = PEDFACDESPAIS.idPais)
	LEFT JOIN MetodosValoracion     PEDFACMV        WITH(NOLOCK) ON (PEDFACTURAS.idValoracion      = PEDFACMV.IdValoracion)
	LEFT JOIN Clientes              PEDFACCLI       WITH(NOLOCK) ON (PEDFACTURAS.idCliente         = PEDFACCLI.idCliente)
	LEFT JOIN EntidadesFederativas  PEDFACCLIEF     WITH(NOLOCK) ON (PEDFACCLI.idEntidad           = PEDFACCLIEF.idEntidad)
	LEFT JOIN Paises                PEDFACCLIPAIS   WITH(NOLOCK) ON (PEDFACCLI.idPais              = PEDFACCLIPAIS.idPais)
	LEFT JOIN Agencias              PEDFACAG        WITH(NOLOCK) ON (PEDFACTURAS.idAgencia         = PEDFACAG.IdAgencia)
	LEFT JOIN Aduanas               PEDFACAGAD      WITH(NOLOCK) ON (PEDFACAG.idAduana             = PEDFACAGAD.idAduana)
	LEFT JOIN Monedas_Equivalencias PEDFACMONEQ     WITH(NOLOCK) ON (PEDFACTURAS.idEquivalencia    = PEDFACMONEQ.idEquivalencia)
	LEFT JOIN EstatusFactura        PEDFACESTFAC    WITH(NOLOCK) ON (PEDFACTURAS.idEstatus         = PEDFACESTFAC.idEstatus)
	LEFT JOIN Paises                PEDFACPAISPROV  WITH(NOLOCK) ON (PEDFACTURAS.idPaisProveedor   = PEDFACPAISPROV.idPais)
	LEFT JOIN Paises                PEDFACPAISPROC  WITH(NOLOCK) ON (PEDFACTURAS.idPaisProcedencia = PEDFACPAISPROC.idPais)
	LEFT JOIN TiposVinculacion      PEDFACTIPOSVIN  WITH(NOLOCK) ON (PEDFACTURAS.idVinculacion     = PEDFACTIPOSVIN.idVinculacion)
	LEFT JOIN CentroCosto           PEDFACCENTROCOS WITH(NOLOCK) ON (PEDFACTURAS.idCentroCosto     = PEDFACCENTROCOS.idCentroCosto)
	LEFT JOIN Paises                PEDFACPAISMONSE WITH(NOLOCK) ON (PEDFACTURAS.idPaisMonSeguros  = PEDFACPAISMONSE.idPais)
	LEFT JOIN Paises                PEDFACPAISMONEM WITH(NOLOCK) ON (PEDFACTURAS.idPaisMonEmbalaje = PEDFACPAISMONEM.idPais)
	LEFT JOIN Paises                PEDFACPAISMONFL WITH(NOLOCK) ON (PEDFACTURAS.idPaisMonFletes   = PEDFACPAISMONFL.idPais)
	LEFT JOIN Paises                PEDFACPAISMONOI WITH(NOLOCK) ON (PEDFACTURAS.idPaisMonOtrosIncrement   = PEDFACPAISMONOI.idPais)

