using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CLLAIntelligentSausage.Modelos.Enumerados
{
	public enum ExpedienteDigitalTipoArchivo
	{
		PEDIMENTO_SIMPLIFICADO = 1,
		PEDIMENTO_BORRADOR = 2,
		PEDIMENTO_ORIGINAL = 3,
		VALIDACION_ENVIO = 4,
		VALIDACION_RESPUESTA = 5,
		PAGO_ENVIO = 6,
		PAGO_RESPUESTA = 7,
		COVE_XML = 8,
		COVE_IMPRESO = 9,
		COVE_ACUSE = 10,
		REMESA_RELACION_DE_FACTURAS = 11,
		REMESA_SIMPLIFICADO = 12,
		DIGITALIZACION_DOCUMENTO = 13,
		DIGITALIZACION_XML_ENVIO = 14,
		DIGITALIZACION_XML_RESPUESTA = 15,
		DIGITALIZACION_ACUSE_IMPRESO = 16,
		DODA_IMPRESO = 17,
		DODA_XML_ENVIO = 18,
		DODA_XML_RESPUESTA = 19,
		MANIFESTACION_DE_VALOR = 20,
		HOJA_DE_CALCULO = 21,
		RELACION_GUIAS_Y_FACTURAS = 22,
		CFD_PDF = 23,
		CFD_XML = 24,
		CUENTA_DE_GASTOS = 25,
		DODA_AVISO_CONSOLIDADO_IMPRESO = 26,
		DODA_AVISO_CONSOLIDADO_XML_ENVIO = 27,
		DODA_AVISO_CONSOLIDADO_XML_RESPUESTA = 28,
		GASTO_COMPROBADO_PDF = 29,
		GUIAS_BL = 30,
		FACTURAS_COMERCIALES = 31,
		ESCANEO_MANUAL = 32,
		FOTO_DE_PREVIO = 33,
		GASTO_COMPROBADO_XML = 34
	}
}
