SELECT
	 ASGFAC.idReferencia
	,PEDPART.idPartida [idPartida]
	,PEDPART.idFactura [idFactura]
	,PEDPART.idParte [idParte]
	,PADPARTPARTES.Clave AS ParteClave
	,PADPARTPARTES.pt_Descripcion AS ParteDescripcion
	,PEDPART.Descripcion [Descripcion]
	,PEDPART.Marca [Marca]
	,PEDPART.Modelo [Modelo]
	,PEDPART.NoSerie [NoSerie]
	,PEDPART.CantidadComercial [CantidadComercial]
	,PEDPART.idUMC [idUMC]
	,PEDPARTUM.ClaveUnidad [UnidadMedidaComercialClaveIUnidad]
	,PEDPARTUM.Descripcion [UnidadMedidaComercialDescripcion]
	,PEDPARTUM.Abreviacion [UnidadMedidaComercialAbreviacion]
	,PEDPARTUM.Abreviacion2 [UnidadMedidaComercialAbreviacion2]
	,PEDPARTUM.ClaveCOVE [UnidadMedidaComercialClaveCOVE]
	,PEDPARTUM.UMCOVEValidas [UnidadMedidaComercialUMCOVEValidas]
	,PEDPART.ImporteME [ImporteME]
	,PEDPART.ImporteUSD [ImporteUSD]
	,PEDPART.ValorMciaME [ValorMciaME]
	,PEDPART.ValorMciaUSD [ValorMciaUSD]
	,PEDPART.ValorAgregadoUSD [ValorAgregadoUSD]
	,PEDPART.PesoBruto [PesoBruto]
	,PEDPART.idPaisOrigen [idPaisOrigen]
	,PEDPARTPAIS.ClaveM3 [PaisOrigenClaveM3]
	,PEDPARTPAIS.NombrePais [PaisOrigenNombrePais]
	,PEDPART.idFraccion [idFraccion]
	,PEDPARTTIGIE.Fraccion [TIGIEFraccion]
	,PEDPARTTIGIE.tg_Descripcion [TIGIEtg_Descripcion]
	,PEDPARTTIGIE.idUnidad [TIGIEidUnidad]
	,PEDPARTTIGIEUM.ClaveUnidad [TGIEUnidadClaveIUnidad]
	,PEDPARTTIGIEUM.Descripcion [TGIEUnidadDescripcion]
	,PEDPARTTIGIEUM.Abreviacion [TGIEUnidadAbreviacion]
	,PEDPARTTIGIEUM.Abreviacion2 [TGIEUnidadAbreviacion2]
	,PEDPARTTIGIEUM.ClaveCOVE [TGIEUnidadClaveCOVE]
	,PEDPARTTIGIEUM.UMCOVEValidas [TGIEUnidadUMCOVEValidas]
	,PEDPART.CantidadTarifa [CantidadTarifa]
	,PEDPART.idIdentificador [idIdentificador]
	,PEDPARTIDENT.Identificador [IdentificadorIdentificador]
	,PEDPARTIDENT.it_Descripcion [IdentificadoritDescripcion]
	,PEDPARTIDENT.Nivel [IdentificadorNivel]
	,PEDPART.Complemento [Complemento]
	,PEDPART.Desaduanamiento [Desaduanamiento]
	,PEDPART.idOrdenFraccion [idOrdenFraccion]
	,PEDPART.CantidadSaldo [CantidadSaldo]
	,PEDPART.Explosionado [Explosionado]
	,PEDPART.EstatusPPS [EstatusPPS]
	,PEDPART.NOTA_1 [NOTA_1]
	,PEDPART.NOTA_2 [NOTA_2]
	,PEDPART.NOTA_3 [NOTA_3]
	,PEDPART.NOTA_4 [NOTA_4]
	,PEDPART.NOTA_5 [NOTA_5]
	,PEDPART.PrecioUnitario [PrecioUnitario]
	,PEDPART.ValorNoOriginario [ValorNoOriginario]
	,PEDPART.ValorRetorno [ValorRetorno]
	,PEDPART.Commodity [Commodity]
	,PEDPART.Bultos [Bultos]
	,PEDPART.idPartidaOriginal [idPartidaOriginal]
	,PEDPART.OrdenCompra [OrdenCompra]
	,PEDPART.idIdentificador2 [idIdentificador2]
	,PEDPARTIDENT2.Identificador [Identificador2Identificador]
	,PEDPARTIDENT2.it_Descripcion [Identificador2itDescripcion]
	,PEDPARTIDENT2.Nivel [Identificador2Nivel]
	,PEDPART.Complemento2_1 [Complemento2_1]
	,PEDPART.Complemento2_2 [Complemento2_2]
	,PEDPART.Comlpemento2_3 [Comlpemento2_3]
	,PEDPART.idIdentificador3 [idIdentificador3]
	,PEDPARTIDENT3.Identificador [Identificador3Identificador]
	,PEDPARTIDENT3.it_Descripcion [Identificador3itDescripcion]
	,PEDPARTIDENT3.Nivel [Identificador3Nivel]
	,PEDPART.Complemento3_1 [Complemento3_1]
	,PEDPART.Complemento3_2 [Complemento3_2]
	,PEDPART.Complemento3_3 [Complemento3_3]
	,PEDPART.idUnidadCOVE [idUnidadCOVE]
	,PEDPARTUMCOVE.Clave [UnidadCOVEClave]
	,PEDPARTUMCOVE.Descripcion [UnidadCOVEDescripcion]
	,PEDPARTUMCOVE.Abreviacion [UnidadCOVEAbreviacion]
	,PEDPART.CantidadCOVE [CantidadCOVE]
	,PEDPART.DescripcionCOVE [DescripcionCOVE]
	,PEDPART.idValoracion [idValoracion]
	,PEDPARTMETVAL.ClaveValoracion [ValoracionClaveValoracion]
	,PEDPARTMETVAL.mv_Descripcion [Valoracionmv_Descripcion]
	,PEDPART.ValorCOVE [ValorCOVE]
	,PEDPART.subModelo [subModelo]
	,PEDPART.Lote [Lote]
	,PEDPART.POCantidad [POCantidad]
	,PEDPART.PartePreCaptura [PartePreCaptura]
	,PEDPART.CertificaOrigen [CertificaOrigen]
	,PEDPART.Complemento2 [Complemento2]
	,PEDPART.Complemento3 [Complemento3]
	,PEDPART.idCategoria [idCategoria]
	,PEDPART.idTipoDeMercancia [idTipoDeMercancia]
	,NULL [TipoDeMercancia]
	,PEDPARTTIPMER.Clave [TipoDeMercanciaClave]
	,PEDPARTTIPMER.Descripcion [TipoDeMercanciaDescripcion]
	,NULL [TipoDeMercanciaClaveTipoMercancia]
	,NULL [TipoDeMercanciaNombreTipoMercancia]
FROM BitacoraExtraccionSysExpertPedimento BEP
	JOIN AsignacionFacturas            ASGFAC              WITH(NOLOCK) ON (BEP.idReferencia               = ASGFAC.idReferencia)
	JOIN Ped_Facturas                  PEDFAC              WITH(NOLOCK) ON (ASGFAC.idFactura               = PEDFAC.idFactura)
	JOIN Ped_Partidas                  PEDPART             WITH(NOLOCK) ON (PEDFAC.idFactura               = PEDPART.idFactura)
	LEFT JOIN Partes                   PADPARTPARTES       WITH(NOLOCK) ON (PEDPART.idParte                = PADPARTPARTES.idParte)
	LEFT JOIN UnidadesMedida           PEDPARTUM           WITH(NOLOCK) ON (PEDPART.idUMC                  = PEDPARTUM.idUnidad)
	LEFT JOIN Paises                   PEDPARTPAIS         WITH(NOLOCK) ON (PEDPART.idPaisOrigen           = PEDPARTPAIS.idPais)
	LEFT JOIN TIGIE                    PEDPARTTIGIE        WITH(NOLOCK) ON (PEDPART.idFraccion             = PEDPARTTIGIE.idFraccion)
	LEFT JOIN UnidadesMedida           PEDPARTTIGIEUM      WITH(NOLOCK) ON (PEDPARTTIGIE.idUnidad          = PEDPARTTIGIEUM.idUnidad)
	LEFT JOIN Identificadores          PEDPARTIDENT        WITH(NOLOCK) ON (PEDPART.idIdentificador        = PEDPARTIDENT.idIdentificador)
	LEFT JOIN Identificadores          PEDPARTIDENT2       WITH(NOLOCK) ON (PEDPART.idIdentificador2       = PEDPARTIDENT2.idIdentificador)
	LEFT JOIN Identificadores          PEDPARTIDENT3       WITH(NOLOCK) ON (PEDPART.idIdentificador3       = PEDPARTIDENT3.idIdentificador)
	LEFT JOIN UnidadesMedidaCOVE       PEDPARTUMCOVE       WITH(NOLOCK) ON (PEDPART.idUnidadCOVE           = PEDPARTUMCOVE.idUnidadCOVE)
	LEFT JOIN MetodosValoracion        PEDPARTMETVAL       WITH(NOLOCK) ON (PEDPART.idValoracion           = PEDPARTMETVAL.IdValoracion)
	LEFT JOIN TipoDeMercancia          PEDPARTTIPMER       WITH(NOLOCK) ON (PEDPART.idTipoDeMercancia      = PEDPARTTIPMER.idTipoDeMercancia)