USE [DW_SysExpert]
GO

/****** Object:  Table [dbo].[Pedimento]    Script Date: 26/09/2020 12:17:36 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Pedimento]') AND type in (N'U'))
DROP TABLE [dbo].[Pedimento]
GO

/****** Object:  Table [dbo].[Pedimento]    Script Date: 26/09/2020 12:17:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pedimento](
	[idPedimento] [int] IDENTITY(1,1) NOT NULL,
	[idReferencia] [int] NOT NULL,
	[FechaEntrada] [datetime] NULL,
	[FechaPago] [datetime] NULL,
	[FechaExtraccion] [datetime] NULL,
	[FechaPresentacion] [datetime] NULL,
	[FechaIMP. EUA/CAN] [datetime] NULL,
	[FechaOriginal] [datetime] NULL,
	[idAgencia] [int] NOT NULL,
	[AgenciaPatente] [varchar](4) NULL,
	[AgenciaAduanaidAduana] [int] NULL,
	[AgenciaAduanaClaveAduana] [varchar](3) NULL,
	[AgenciaAduanaNombreAduana] [nchar](130) NULL,
	[NumeroReferencia] [varchar](30) NOT NULL,
	[NumeroPedimento] [varchar](12) NOT NULL,
	[idTipoOperacion] [int] NOT NULL,
	[TipoOperacionTipoOperacion] [int] NULL,
	[TipoOperacionOp_Clave] [varchar](3) NULL,
	[TipoOperacionOp_Descripcion] [varchar](15) NULL,
	[Rectificacion] [bit] NOT NULL,
	[idRectificacion] [int] NULL,
	[RectificacionidCveDocRectificacion] [int] NULL,
	[RectificacionCveDocRectificacionClave] [varchar](3) NULL,
	[RectificacionidCveDocRectificacionIdGrupo] [int] NULL,
	[RectificacionidCveDocRectificacionRegimenrg_Clave] [varchar](3) NULL,
	[RectificacionidCveDocRectificacionRegimenrg_Descripcion] [varchar](120) NULL,
	[RectificacionPedimentoOriginal] [varchar](12) NULL,
	[RectificacionidCveDocOriginal] [int] NULL,
	[RectificacionCveDocOriginalClave] [nchar](10) NULL,
	[RectificacionCveDocOriginalIdGrupo] [nchar](10) NULL,
	[RectificacionCveDocOriginalRegimenrg_Clave] [varchar](3) NULL,
	[RectificacionCveDocOriginalRegimenrg_Descripcion] [varchar](120) NULL,
	[RectificacionFechaRectificacion] [nchar](10) NULL,
	[RectificacionidAduanaOriginal] [int] NULL,
	[RectificacionAduanaOriginalClave] [varchar](3) NULL,
	[RectificacionAduanaOriginalNombre] [varchar](130) NULL,
	[RectificacionFactorActualizacion] [decimal](6, 4) NULL,
	[RectificacionTasaRecargos] [decimal](10, 5) NULL,
	[RectificacionFactorActualizacionEnt] [decimal](9, 4) NULL,
	[RectifiacionidReferenciaOriginal] [int] NULL,
	[RectificacionReferenciaOriginalNumeroReferencia] [varchar](30) NULL,
	[RectificacionDiferenciaDTAImporte] [float] NULL,
	[RectificacionDiferenciaDTAidFormaPago] [int] NULL,
	[RectificacionDiferenciaDTAClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaDTAFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaCCImporte] [float] NULL,
	[RectificacionDiferenciaCCidFormaPago] [int] NULL,
	[RectificacionDiferenciaCCClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaCCFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaIVAImporte] [float] NULL,
	[RectificacionDiferenciaIVAidFormaPago] [int] NULL,
	[RectificacionDiferenciaIVAClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaIVAFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaIEPSImporte] [float] NULL,
	[RectificacionDiferenciaIEPSidFormaPago] [int] NULL,
	[RectificacionDiferenciaIEPSClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaIEPSFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaIGI/IGEImporte] [float] NULL,
	[RectificacionDiferenciaIGI/IGEidFormaPago] [int] NULL,
	[RectificacionDiferenciaIGI/IGEClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaIGI/IGEFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaRECImporte] [float] NULL,
	[RectificacionDiferenciaRECidFormaPago] [int] NULL,
	[RectificacionDiferenciaRECClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaRECFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaMULTImporte] [float] NULL,
	[RectificacionDiferenciaMULTidFormaPago] [int] NULL,
	[RectificacionDiferenciaMULTClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaMULTFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferencia303Importe] [float] NULL,
	[RectificacionDiferencia303idFormaPago] [int] NULL,
	[RectificacionDiferencia303ClaveFormaPago] [smallint] NULL,
	[RectificacionDiferencia303FormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaRTImporte] [float] NULL,
	[RectificacionDiferenciaRTidFormaPago] [int] NULL,
	[RectificacionDiferenciaRTClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaRTFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaPRVImporte] [float] NULL,
	[RectificacionDiferenciaPRVidFormaPago] [int] NULL,
	[RectificacionDiferenciaPRVClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaPRVFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaEURImporte] [float] NULL,
	[RectificacionDiferenciaEURidFormaPago] [int] NULL,
	[RectificacionDiferenciaEURClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaEURFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaECIImporte] [float] NULL,
	[RectificacionDiferenciaECIidFormaPago] [int] NULL,
	[RectificacionDiferenciaECIClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaECIFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaCNTImporte] [float] NULL,
	[RectificacionDiferenciaCNTidFormaPago] [int] NULL,
	[RectificacionDiferenciaCNTClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaCNTFormaPagofp_Descripcion] [varchar](35) NULL,
	[RectificacionDiferenciaIVA/PRVImporte] [float] NULL,
	[RectificacionDiferenciaIVA/PRVidFormaPago] [int] NULL,
	[RectificacionDiferenciaIVA/PRVClaveFormaPago] [smallint] NULL,
	[RectificacionDiferenciaIVA/PRVFormaPagofp_Descripcion] [varchar](35) NULL,
	[idClave] [int] NOT NULL,
	[CveDocClave] [varchar](3) NULL,
	[CveDocIdGrupo] [int] NULL,
	[CveDocRegimenrg_Clave] [varchar](3) NULL,
	[CveDocRegimenrg_Descripcion] [varchar](120) NULL,
	[idAduanaEntSal] [int] NULL,
	[AduanaEntSalClaveAduana] [varchar](3) NULL,
	[AduanaEntSalNombreAduana] [varchar](130) NULL,
	[idAduanaDespacho] [int] NOT NULL,
	[AduanaDespachoClave] [varchar](3) NULL,
	[AduanaDespachoNombre] [varchar](3) NULL,
	[idTipoCambio] [int] NOT NULL,
	[TipoCambioFecha] [datetime] NULL,
	[TipoCambioValor] [money] NULL,
	[idCliente] [int] NOT NULL,
	[ClienteClaveCliente] [int] NULL,
	[ClienteRazonSocial] [varchar](120) NULL,
	[ClienteRFC] [varchar](13) NULL,
	[ClienteCURP] [varchar](18) NULL,
	[ClienteDomicilio] [varchar](250) NULL,
	[ClienteCalle] [varchar](80) NULL,
	[ClienteNumeroExterior] [varchar](20) NULL,
	[ClienteNumeroInterior] [varchar](20) NULL,
	[ClienteColonia] [varchar](50) NULL,
	[ClienteCodigoPostal] [varchar](10) NULL,
	[ClienteCiudad] [varchar](80) NULL,
	[ClienteidEntidad] [int] NULL,
	[ClienteClaveEntidad] [varchar](3) NULL,
	[ClienteEntidadFederativa] [varchar](30) NULL,
	[ClienteidPais] [int] NULL,
	[ClientePaisClaveM3] [varchar](3) NULL,
	[ClientePaisNombrePais] [varchar](60) NULL,
	[idClienteFacturar] [int] NULL,
	[ClienteFacturarClaveCliente] [int] NULL,
	[ClienteFacturarRazonSocial] [varchar](120) NULL,
	[ClienteFacturarRFC] [varchar](13) NULL,
	[ClienteFacturarCURP] [varchar](18) NULL,
	[ClienteFacturarDomicilio] [varchar](250) NULL,
	[ClienteFacturarCalle] [varchar](80) NULL,
	[ClienteFacturarNumeroExterior] [varchar](20) NULL,
	[ClienteFacturarNumeroInterior] [varchar](20) NULL,
	[ClienteFacturarColonia] [varchar](50) NULL,
	[ClienteFacturarCodigoPostal] [varchar](10) NULL,
	[ClienteFacturarCiudad] [varchar](80) NULL,
	[ClienteFacturaridEntidad] [int] NULL,
	[ClienteFacturarClaveEntidad] [varchar](3) NULL,
	[ClienteFacturarEntidadFederativa] [varchar](30) NULL,
	[ClienteFacturaridPais] [int] NULL,
	[ClienteFacturarPaisClaveM3] [varchar](3) NULL,
	[ClienteFacturarPaisNombrePais] [varchar](60) NULL,
	[idMTEntrada] [int] NULL,
	[MTEntradaClaveTransporte] [smallint] NULL,
	[MTEntradaDescripcion] [varchar](45) NULL,
	[idMTSalida] [int] NULL,
	[MTSalidaClaveTransporte] [smallint] NULL,
	[MTSalidaDescripcion] [varchar](45) NULL,
	[idMTArribo] [int] NULL,
	[MTArriboClaveTransporte] [smallint] NULL,
	[MTArriboDescripcion] [varchar](45) NULL,
	[ValorSegurosMN] [money] NOT NULL,
	[DescuentosAdmisiblesUSD] [money] NOT NULL,
	[FactorActualizacion] [decimal](6, 4) NOT NULL,
	[AfectaIncrementables] [bit] NOT NULL,
	[Bultos] [int] NOT NULL,
	[MarcasNumeros] [varchar](150) NOT NULL,
	[idDestino] [int] NOT NULL,
	[DestinoClave] [smallint] NULL,
	[DestinoDescripcion] [varchar](60) NULL,
	[idTramitador] [int] NULL,
	[TramitadorClave] [int] NULL,
	[TramitadorNombre] [varchar](80) NULL,
	[TramitadorRFC] [varchar](13) NULL,
	[TramitadorCURP] [varchar](18) NULL,
	[Observaciones] [varchar](7000) NOT NULL,
	[Acuse] [varchar](8) NOT NULL,
	[ArchivoValidacion] [varchar](15) NOT NULL,
	[Bacuse] [varchar](20) NOT NULL,
	[BArchivoValidacion] [varchar](15) NOT NULL,
	[BPagoFecha] [datetime] NULL,
	[BpagoHora] [varchar](8) NOT NULL,
	[Bcaja] [smallint] NOT NULL,
	[BOperacionBancaria] [varchar](14) NOT NULL,
	[idBancos] [int] NULL,
	[BancosClave] [int] NULL,
	[BancosNombre] [varchar](120) NULL,
	[Desaduanamiento] [varchar](10) NOT NULL,
	[DesaduanamientoFecha] [datetime] NULL,
	[idUsuarioDesaduana] [int] NULL,
	[UsuarioDesaduanaUSU_NAME] [varchar](50) NULL,
	[Aleatorio] [char](1) NOT NULL,
	[ClaveVista] [varchar](4) NOT NULL,
	[idPrueba] [int] NULL,
	[PruebaClave] [varchar](1) NULL,
	[PruebaDescripcion] [varchar](300) NULL,
	[FechaPrueba] [datetime] NULL,
	[Anio] [smallint] NOT NULL,
	[PedimentoUSACAN] [varchar](14) NOT NULL,
	[MV_Comisiones] [int] NOT NULL,
	[MV_FletesySeguros] [int] NOT NULL,
	[MV_CargayDescarga] [int] NOT NULL,
	[MV_MaterialesAportados] [int] NOT NULL,
	[MV_TecnologiaAportada] [int] NOT NULL,
	[MV_Regalias] [int] NOT NULL,
	[MV_Reversiones] [int] NOT NULL,
	[MV_GastosNoRelacionados] [int] NOT NULL,
	[MV_FletesySegurosNI] [int] NOT NULL,
	[MV_GastosConstruccion] [int] NOT NULL,
	[MV_InstalacionArmado] [int] NOT NULL,
	[MV_Contribuciones] [decimal](12, 0) NOT NULL,
	[MV_Dividendos] [int] NOT NULL,
	[TotalVehiculos] [smallint] NOT NULL,
	[PesoBruto] [decimal](14, 3) NOT NULL,
	[idPrevalidador] [int] NULL,
	[PrevalidadorClavePrevalidador] [char](3) NULL,
	[PrevalidadorNombrePrevalidador] [char](90) NULL,
	[FirmaCAAAREM] [varchar](8) NOT NULL,
	[idSemana] [int] NULL,
	[SemanaFechaInicial] [datetime] NULL,
	[SemanaFechaFinal] [datetime] NULL,
	[Semana] [smallint] NULL,
	[ContadorRemesas] [int] NOT NULL,
	[FletesUSD] [money] NOT NULL,
	[SegurosUSD] [money] NOT NULL,
	[EmbalajeUSD] [money] NOT NULL,
	[OtrosIncrementablesUSD] [money] NOT NULL,
	[FactorIncrementables] [float] NOT NULL,
	[TipoActualizacion] [smallint] NOT NULL,
	[FechaExportacion] [datetime] NULL,
	[ITN] [varchar](15) NULL,
	[ITN_Valida] [bit] NULL,
	[Producto] [varchar](15) NULL,
	[Planta] [varchar](20) NULL,
	[Rubro] [varchar](10) NULL,
	[ClaveCuentaPago] [varchar](5) NULL,
	[idCuentaConsolidada] [int] NULL,
	[CuentaConsolidadaConsecutivoCuenta] [varchar](30) NULL,
	[CuentaConsolidadaFechaCuenta] [datetime] NULL,
	[NuevasObservaciones] [text] NULL,
	[RFCFacturaServicios] [varchar](13) NULL,
	[TipoDeCambio] [money] NULL,
	[ClaveRegimen] [varchar](3) NULL,
	[EstatusGF] [int] NULL,
	[IncrementablesManual] [bit] NULL,
	[Folio] [varchar](30) NULL,
	[AgrupacionManual] [bit] NULL,
	[OctavoResolutivo] [bit] NULL,
	[Glosa] [smallint] NULL,
	[FletesME] [decimal](18, 2) NULL,
	[SegurosME] [decimal](18, 2) NULL,
	[EmbalajeME] [decimal](18, 2) NULL,
	[OtrosIncrementME] [decimal](18, 2) NULL,
	[idPaisMonFletes] [int] NULL,
	[PaisMonFletesClaveM3] [varchar](3) NULL,
	[PaisMonFletesNombrePais] [varchar](60) NULL,
	[PaisMonFletesClaveMoneda] [varchar](3) NULL,
	[PaisMonFletesNombreMoneda] [varchar](30) NULL,
	[idPaisMonSeguros] [int] NULL,
	[PaisMonSegurosClaveM3] [varchar](3) NULL,
	[PaisMonSegurosNombrePais] [varchar](60) NULL,
	[PaisMonSegurosClaveMoneda] [varchar](3) NULL,
	[PaisMonSegurosNombreMoneda] [varchar](30) NULL,
	[idPaisMonEmbalaje] [int] NULL,
	[PaisMonEmbalajeClaveM3] [varchar](3) NULL,
	[PaisMonEmbalajeNombrePais] [varchar](60) NULL,
	[PaisMonEmbalajeClaveMoneda] [varchar](3) NULL,
	[PaisMonEmbalajeNombreMoneda] [varchar](30) NULL,
	[idPaisMonOtrosIncrement] [int] NULL,
	[PaisMonOtrosIncrementClaveM3] [varchar](3) NULL,
	[PaisMonOtrosIncrementNombrePais] [varchar](60) NULL,
	[PaisMonOtrosIncrementClaveMoneda] [varchar](3) NULL,
	[PaisMonOtrosIncrementNombreMoneda] [varchar](30) NULL,
	[LineaCaptura] [varchar](50) NULL,
	[TotalImportePagar] [decimal](18, 2) NULL,
	[ArchivoConfimacionPago] [varchar](12) NULL,
	[AcuseConfirmacionPago] [varchar](8) NULL,
	[NumeroTransaccionSAT] [varchar](20) NULL,
	[idClientesDomicilios] [int] NULL,
	[ClienteDomicilioDomicilio] [varchar](250) NULL,
	[ClienteDomicilioCalle] [varchar](80) NULL,
	[ClienteDomicilioNumeroExterior] [varchar](20) NULL,
	[ClienteDomicilioNumeroInterior] [varchar](20) NULL,
	[ClienteDomicilioColonia] [varchar](50) NULL,
	[ClienteDomicilioCodigoPostal] [varchar](10) NULL,
	[ClienteDomicilioCiudad] [varchar](80) NULL,
	[ClienteDomicilioidEntidad] [int] NULL,
	[ClienteDomicilioClaveEntidad] [varchar](3) NULL,
	[ClienteDomicilioEntidadFederativa] [varchar](30) NULL,
	[ClienteDomicilioidPais] [int] NULL,
	[ClienteDomicilioPaisClaveM3] [varchar](3) NULL,
	[ClienteDomicilioPaisNombrePais] [varchar](60) NULL,
	[ClienteDomicilioMunicipio] [varchar](120) NULL,
	[ClienteDomicilioidMunicipio] [varchar](120) NULL,
	[ClienteDomicilioMunicipioClaveMunipio] [varchar](5) NULL,
	[ClienteDomicilioMunicipioMunipio] [varchar](40) NULL,
	[ClienteDomicilioidColonia] [int] NULL,
	[ClienteDomicilioColoniaClaveColonia] [varchar](15) NULL,
	[ClienteDomicilioColoniaNombre] [varchar](120) NULL,
	[ReferenciaMaster] [bit] NULL,
	[idReferenciaMaster] [int] NULL,
	[ReferenciaMasterNumeroReferencia] [varchar](30) NULL,
	[DTAPorcentajeAplicar] [decimal](9, 5) NULL,
	[DTATipoTasa] [nchar](10) NULL,
	[DTAidFormaPago] [int] NULL,
	[DTAFormaPagoClaveFormaPago] [smallint] NULL,
	[DTAFormaPagofp_Descripcion] [varchar](35) NULL,
	[DTAidTipoTasa] [int] NULL,
	[DTATipoTastaTipoTasa] [smallint] NULL,
	[DTATipoTasaDescripcion] [varchar](51) NULL,
	[DTATasaContribucion] [decimal](12, 5) NULL,
	[RECPorcentajeAplicar] [decimal](9, 5) NULL,
	[RECTipoTasa] [nchar](10) NULL,
	[RECidFormaPago] [int] NULL,
	[RECFormaPagoClaveFormaPago] [smallint] NULL,
	[RECFormaPagofp_Descripcion] [varchar](35) NULL,
	[RECidTipoTasa] [int] NULL,
	[RECTipoTastaTipoTasa] [smallint] NULL,
	[RECTipoTasaDescripcion] [varchar](51) NULL,
	[RECTasaContribucion] [decimal](12, 5) NULL,
	[OTROSPorcentajeAplicar] [decimal](9, 5) NULL,
	[OTROSTipoTasa] [nchar](10) NULL,
	[OTROSidFormaPago] [int] NULL,
	[OTROSFormaPagoClaveFormaPago] [smallint] NULL,
	[OTROSFormaPagofp_Descripcion] [varchar](35) NULL,
	[OTROSidTipoTasa] [int] NULL,
	[OTROSTipoTastaTipoTasa] [smallint] NULL,
	[OTROSTipoTasaDescripcion] [varchar](51) NULL,
	[OTROSTasaContribucion] [decimal](12, 5) NULL,
	[DTIPorcentajeAplicar] [decimal](9, 5) NULL,
	[DTITipoTasa] [nchar](10) NULL,
	[DTIidFormaPago] [int] NULL,
	[DTIFormaPagoClaveFormaPago] [smallint] NULL,
	[DTIFormaPagofp_Descripcion] [varchar](35) NULL,
	[DTIidTipoTasa] [int] NULL,
	[DTITipoTastaTipoTasa] [smallint] NULL,
	[DTITipoTasaDescripcion] [varchar](51) NULL,
	[DTITasaContribucion] [decimal](12, 5) NULL,
	[MULTPorcentajeAplicar] [decimal](9, 5) NULL,
	[MULTTipoTasa] [nchar](10) NULL,
	[MULTidFormaPago] [int] NULL,
	[MULTFormaPagoClaveFormaPago] [smallint] NULL,
	[MULTFormaPagofp_Descripcion] [varchar](35) NULL,
	[MULTiMULTpoTasa] [int] NULL,
	[MULTTipoTastaTipoTasa] [smallint] NULL,
	[MULTTipoTasaDescripcion] [varchar](51) NULL,
	[MULTTasaContribucion] [decimal](12, 5) NULL,
	[RTPorcentajeAplicar] [decimal](9, 5) NULL,
	[RTTipoTasa] [nchar](10) NULL,
	[RTidFormaPago] [int] NULL,
	[RTFormaPagoClaveFormaPago] [smallint] NULL,
	[RTFormaPagofp_Descripcion] [varchar](35) NULL,
	[RTiRTpoTasa] [int] NULL,
	[RTTipoTastaTipoTasa] [smallint] NULL,
	[RTTipoTasaDescripcion] [varchar](51) NULL,
	[RTTasaContribucion] [decimal](12, 5) NULL,
	[PRVPorcentajeAplicar] [decimal](9, 5) NULL,
	[PRVTipoTasa] [nchar](10) NULL,
	[PRVidFormaPago] [int] NULL,
	[PRVFormaPagoClaveFormaPago] [smallint] NULL,
	[PRVFormaPagofp_Descripcion] [varchar](35) NULL,
	[PRViPRVpoTasa] [int] NULL,
	[PRVTipoTastaTipoTasa] [smallint] NULL,
	[PRVTipoTasaDescripcion] [varchar](51) NULL,
	[PRVTasaContribucion] [decimal](12, 5) NULL,
	[REUPorcentajeAplicar] [decimal](9, 5) NULL,
	[REUTipoTasa] [nchar](10) NULL,
	[REUidFormaPago] [int] NULL,
	[REUFormaPagoClaveFormaPago] [smallint] NULL,
	[REUFormaPagofp_Descripcion] [varchar](35) NULL,
	[REUiREUpoTasa] [int] NULL,
	[REUTipoTastaTipoTasa] [smallint] NULL,
	[REUTipoTasaDescripcion] [varchar](51) NULL,
	[REUTasaContribucion] [decimal](12, 5) NULL,
	[ECIPorcentajeAplicar] [decimal](9, 5) NULL,
	[ECITipoTasa] [nchar](10) NULL,
	[ECIidFormaPago] [int] NULL,
	[ECIFormaPagoClaveFormaPago] [smallint] NULL,
	[ECIFormaPagofp_Descripcion] [varchar](35) NULL,
	[ECIiECIpoTasa] [int] NULL,
	[ECITipoTastaTipoTasa] [smallint] NULL,
	[ECITipoTasaDescripcion] [varchar](51) NULL,
	[ECITasaContribucion] [decimal](12, 5) NULL,
	[DFCPorcentajeAplicar] [decimal](9, 5) NULL,
	[DFCTipoTasa] [nchar](10) NULL,
	[DFCidFormaPago] [int] NULL,
	[DFCFormaPagoClaveFormaPago] [smallint] NULL,
	[DFCFormaPagofp_Descripcion] [varchar](35) NULL,
	[DFCiDFCpoTasa] [int] NULL,
	[DFCTipoTastaTipoTasa] [smallint] NULL,
	[DFCTipoTasaDescripcion] [varchar](51) NULL,
	[DFCTasaContribucion] [decimal](12, 5) NULL,
	[ITVPorcentajeAplicar] [decimal](9, 5) NULL,
	[ITVTipoTasa] [nchar](10) NULL,
	[ITVidFormaPago] [int] NULL,
	[ITVFormaPagoClaveFormaPago] [smallint] NULL,
	[ITVFormaPagofp_Descripcion] [varchar](35) NULL,
	[ITViITVpoTasa] [int] NULL,
	[ITVTipoTastaTipoTasa] [smallint] NULL,
	[ITVTipoTasaDescripcion] [varchar](51) NULL,
	[ITVTasaContribucion] [decimal](12, 5) NULL,
	[CNTPorcentajeAplicar] [decimal](9, 5) NULL,
	[CNTTipoTasa] [nchar](10) NULL,
	[CNTidFormaPago] [int] NULL,
	[CNTFormaPagoClaveFormaPago] [smallint] NULL,
	[CNTFormaPagofp_Descripcion] [varchar](35) NULL,
	[CNTiCNTpoTasa] [int] NULL,
	[CNTTipoTastaTipoTasa] [smallint] NULL,
	[CNTTipoTasaDescripcion] [varchar](51) NULL,
	[CNTTasaContribucion] [decimal](12, 5) NULL,
	[IVA/PRVPorcentajeAplicar] [decimal](9, 5) NULL,
	[IVA/PRVTipoTasa] [nchar](10) NULL,
	[IVA/PRVidFormaPago] [int] NULL,
	[IVA/PRVFormaPagoClaveFormaPago] [smallint] NULL,
	[IVA/PRVFormaPagofp_Descripcion] [varchar](35) NULL,
	[IVA/PRViIVA/PRVpoTasa] [int] NULL,
	[IVA/PRVTipoTastaTipoTasa] [smallint] NULL,
	[IVA/PRVTipoTasaDescripcion] [varchar](51) NULL,
	[IVA/PRVTasaContribucion] [decimal](12, 5) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


