//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int IdConfiguracion { get; set; }
        public int ProcesamientoHistoricoDias { get; set; }
        public string GastosComprobadosRutaOrigen { get; set; }
        public string GastosComprobadosRutaDestino { get; set; }
    }
}
