//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaDocumentacion
    {
        public int IdCuentaDocumentacion { get; set; }
        public int ClaveCuenta { get; set; }
        public int ClaveCuentaDocumentoTipo { get; set; }
        public string DocumentoNumero { get; set; }
        public string DocumentoReferenteA { get; set; }
        public Nullable<int> IdEmisorDocumento { get; set; }
        public string EmisorDocumento { get; set; }
        public Nullable<System.DateTime> DocumentoFecha { get; set; }
        public Nullable<System.DateTime> DocumentoFechaVigencia { get; set; }
        public Nullable<decimal> DocumentoImporte { get; set; }
        public string ClaveMoneda { get; set; }
        public Nullable<decimal> TipoDeCambio { get; set; }
        public string ClaveDocumentoOrigen { get; set; }
        public string ClaveDocumentoStatus { get; set; }
    }
}
