//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigitalBitacoraExportacion
    {
        public int IdExpedienteDigitalBitacoraExportacion { get; set; }
        public Nullable<int> IdExpedienteDigitalConfiguracionExportacion { get; set; }
        public Nullable<int> IdExpedienteDigitalArchivo { get; set; }
        public int IdExpedienteDigital { get; set; }
        public int IdExpedienteDigitalTipoExportacion { get; set; }
        public string RutaOrigen { get; set; }
        public string RutaRaizNomenclatura { get; set; }
        public string RutaRaiz { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public string RutaCompletaExportado { get; set; }
        public string Servidor { get; set; }
        public string Puerto { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<System.DateTime> Programacion { get; set; }
        public Nullable<System.DateTime> Exportado { get; set; }
        public Nullable<System.DateTime> Error { get; set; }
        public Nullable<int> ErrorIdExpedienteDigitalEvento { get; set; }
        public string ErrorObservaciones { get; set; }
    
        public virtual ExpedienteDigitalArchivo ExpedienteDigitalArchivo { get; set; }
        public virtual ExpedienteDigitalEvento ExpedienteDigitalEvento { get; set; }
    }
}
