//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigitalConfiguracionCliente
    {
        public int IdExpedienteDigitalConfiguracionCliente { get; set; }
        public int ClaveClienteSysExpert { get; set; }
        public string NomenclaturaRutaRaizCompletado { get; set; }
        public bool Habilitado { get; set; }
        public int IdExpedienteDigitalConfiguracion { get; set; }
    
        public virtual ExpedienteDigitalConfiguracion ExpedienteDigitalConfiguracion { get; set; }
    }
}
