//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpedienteDigital()
        {
            this.ExpedienteDigitalArchivo = new HashSet<ExpedienteDigitalArchivo>();
            this.ExpedienteDigitalBitacora = new HashSet<ExpedienteDigitalBitacora>();
            this.ExpedienteDigitalGastoComprobado = new HashSet<ExpedienteDigitalGastoComprobado>();
            this.ExpedienteDigitalMetaDato = new HashSet<ExpedienteDigitalMetaDato>();
            this.ExpedienteDigitalProcesamiento = new HashSet<ExpedienteDigitalProcesamiento>();
        }
    
        public int IdExpedienteDigital { get; set; }
        public int IdReferenciaSysExpert { get; set; }
        public int IdAgenciaSysExpert { get; set; }
        public bool ExpedienteCompleto { get; set; }
        public bool ExpedienteFinalizado { get; set; }
        public bool ExpedienteSincronizadoSysExpertWeb { get; set; }
        public int ClaveClienteSysExpert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalArchivo> ExpedienteDigitalArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalBitacora> ExpedienteDigitalBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalGastoComprobado> ExpedienteDigitalGastoComprobado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalMetaDato> ExpedienteDigitalMetaDato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalProcesamiento> ExpedienteDigitalProcesamiento { get; set; }
    }
}
