//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigitalGastoComprobado
    {
        public int IdGastoComprobado { get; set; }
        public Nullable<int> IdExpedienteDigital { get; set; }
        public string EmisorNombre { get; set; }
        public string EmisorRFC { get; set; }
        public string Folio { get; set; }
        public string Fecha { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public string RutaArchivoXMLOrigen { get; set; }
        public string RutaArchivoXMLDestino { get; set; }
        public string RutaArchivoPDFOrigen { get; set; }
        public string RutaArchivoPDFDestino { get; set; }
    
        public virtual ExpedienteDigital ExpedienteDigital { get; set; }
    }
}
