//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigitalProcesamientoArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpedienteDigitalProcesamientoArchivo()
        {
            this.ExpedienteDigitalArchivo = new HashSet<ExpedienteDigitalArchivo>();
            this.ExpedienteDigitalMetaDato = new HashSet<ExpedienteDigitalMetaDato>();
        }
    
        public int IdExpedienteDigitalProcesamientoArchivo { get; set; }
        public int IdExpedienteDigitalProcesamiento { get; set; }
        public string ArchivoRutaCompletaOrigen { get; set; }
        public string ArchivoRutaCompletaDestino { get; set; }
        public Nullable<System.DateTime> PrimeraBusqueda { get; set; }
        public Nullable<System.DateTime> Procesado { get; set; }
        public Nullable<System.DateTime> Error { get; set; }
        public Nullable<int> ErrorIdExpedienteDigitalEvento { get; set; }
        public string ErrorObservaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalArchivo> ExpedienteDigitalArchivo { get; set; }
        public virtual ExpedienteDigitalEvento ExpedienteDigitalEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalMetaDato> ExpedienteDigitalMetaDato { get; set; }
    }
}
