//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDigital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpedienteDigital()
        {
            this.ExpedienteDigitalArchivo = new HashSet<ExpedienteDigitalArchivo>();
            this.ExpedienteDigitalGastoComprobado = new HashSet<ExpedienteDigitalGastoComprobado>();
            this.ExpedienteDigitalMetaDato = new HashSet<ExpedienteDigitalMetaDato>();
            this.ExpedienteDigitalProcesamiento = new HashSet<ExpedienteDigitalProcesamiento>();
        }
    
        public int IdExpedienteDigital { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public int IdReferenciaSysExpert { get; set; }
        public int IdAgenciaSysExpert { get; set; }
        public Nullable<int> ClaveClienteSysExpert { get; set; }
        public Nullable<int> ClaveClienteSLAM { get; set; }
        public Nullable<int> ClaveClienteUnica { get; set; }
        public string ClienteRazonSocial { get; set; }
        public string NumeroPedimento { get; set; }
        public string NumeroReferencia { get; set; }
        public string Aduana { get; set; }
        public string Patente { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> TipoOperacion { get; set; }
        public string ClaveDocumento { get; set; }
        public Nullable<bool> PedimentoConsolidado { get; set; }
        public Nullable<System.DateTime> Completado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalArchivo> ExpedienteDigitalArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalGastoComprobado> ExpedienteDigitalGastoComprobado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalMetaDato> ExpedienteDigitalMetaDato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedienteDigitalProcesamiento> ExpedienteDigitalProcesamiento { get; set; }
    }
}
