//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FXpertContext : DbContext
    {
        public FXpertContext()
            : base("name=FXpertContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuentaDocumentacion> CuentaDocumentacion { get; set; }
        public virtual DbSet<CuentaEncabezado> CuentaEncabezado { get; set; }
        public virtual DbSet<FacturaEncabezado> FacturaEncabezado { get; set; }
    
        [DbFunction("FXpertContext", "fnCLLAObtenerFacturaPedimentoAduana240")]
        public virtual IQueryable<fnCLLAObtenerFacturaPedimentoAduana240_Result> fnCLLAObtenerFacturaPedimentoAduana240(string numeroPedimento)
        {
            var numeroPedimentoParameter = numeroPedimento != null ?
                new ObjectParameter("NumeroPedimento", numeroPedimento) :
                new ObjectParameter("NumeroPedimento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnCLLAObtenerFacturaPedimentoAduana240_Result>("[FXpertContext].[fnCLLAObtenerFacturaPedimentoAduana240](@NumeroPedimento)", numeroPedimentoParameter);
        }
    }
}
