//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLLAIntelligentSausage.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExpedienteDigtialProcesamientoArchivoBitacoraPendientes
    {
        public string NumeroReferencia { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string ClaveCliente { get; set; }
        public int IdTipoArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public string Evento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string RutaOrigen { get; set; }
    }
}
