	SELECT 
		NICO.[TIGIE 2012],
		NICO.[TIGIE 2020_(SA 2017)],
		NICO.NICo,
		TIGIE.DESCIPCIÓN,
		TIGIE.[UNIDAD DE MEDIDA],
		TIGIE.IGI,
		TIGIE.IGE,
		TIGIE.OBSERVACIONES
	FROM ExtraccionTIGIE2020NICO     NICO 
		JOIN ExtraccionTIGIE2020      TIGIE ON (NICO.[TIGIE 2020_(SA 2017)] = TIGIE.[FRACCIÓN ARANCELARIA]) 